build_env: &build_env
  working_directory: ~/bigdaddy
  docker:
    - image: circleci/node:12.14.1
version: 2.18
jobs:
  install:
    <<: *build_env
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm-wee
          command: npm ci
      - run:
          name: test
          command: npm test
  deploy:
    <<: *build_env
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: ssh-deploy
          command: |
            echo ${SSH_KNOWN_HOST} > ~/.ssh/known_hosts
            rm -rf ~/bigdaddy/.git
            ssh ${SSH_USER}@${SSH_HOST} -t "mkdir -p '/home/circleci/app' || exit 0"
            scp -r ~/bigdaddy ${SSH_USER}@${SSH_HOST}:/home/circleci/app
            ssh ${SSH_USER}@${SSH_HOST} -t "cd /home/circleci/app/bigdaddy && npm ci && npm run start"
            ssh ${SSH_USER}@${SSH_HOST} -t "chown -R circleci:circleci /home/circleci/app/bigdaddy"
workflows:
  version: 2
  install_and_deploy:
    jobs:
      - install
      - deploy